// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-sections.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function guestyEndpoint() {
  return `${supabaseProjectUrl()}/functions/v1/guesty-beapi`;
}
function publishableKey() {
  return supabasePublishableKey();
}

// src/lib/mcp/tools/list-sections.ts
var list_sections_default = defineTool({
  name: "list_cms_sections",
  title: "List CMS sections",
  description: "List every CMS section and page stored for the site, with its key, label, visibility and sort order.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("cms_content").select("section_key, section_label, is_visible, sort_order, updated_at").order("sort_order", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { sections: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-section.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";
var get_section_default = defineTool2({
  name: "get_cms_section",
  title: "Get CMS section",
  description: "Read the full JSON content of one CMS section or page by its section key.",
  inputSchema: {
    section_key: z.string().trim().min(1).describe("Section key, e.g. 'hero' or 'page:home'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ section_key }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("cms_content").select("section_key, section_label, content, is_visible, sort_order, updated_at").eq("section_key", section_key).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: `No section found for key "${section_key}".` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { section: data }
    };
  }
});

// src/lib/mcp/tools/update-section.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var update_section_default = defineTool3({
  name: "update_cms_section",
  title: "Update CMS section",
  description: "Create or replace the JSON content of a CMS section or page. Overwrites the stored content for that key.",
  inputSchema: {
    section_key: z2.string().trim().min(1).describe("Section key to write, e.g. 'hero' or 'page:home'."),
    content: z2.unknown().describe("The full JSON content object to store for this section."),
    section_label: z2.string().trim().optional().describe("Human-readable label shown in the editor."),
    is_visible: z2.boolean().optional().describe("Whether the section renders on the live site.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ section_key, content, section_label, is_visible }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const row = {
      section_key,
      section_label: section_label ?? section_key,
      content: content ?? {}
    };
    if (typeof is_visible === "boolean") row.is_visible = is_visible;
    const { data, error } = await supabase.from("cms_content").upsert(row, { onConflict: "section_key" }).select("section_key, section_label, is_visible, updated_at");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Saved "${section_key}".` }],
      structuredContent: { section: data?.[0] ?? null }
    };
  }
});

// src/lib/mcp/tools/toggle-section.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var toggle_section_default = defineTool4({
  name: "set_cms_section_visibility",
  title: "Show or hide CMS section",
  description: "Show or hide a CMS section on the live site without changing its content.",
  inputSchema: {
    section_key: z3.string().trim().min(1).describe("Section key to update."),
    is_visible: z3.boolean().describe("True to show the section, false to hide it.")
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ section_key, is_visible }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("cms_content").update({ is_visible }).eq("section_key", section_key).select("section_key, is_visible");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data?.length) {
      return { content: [{ type: "text", text: `No section found for key "${section_key}".` }], isError: true };
    }
    return {
      content: [{ type: "text", text: `"${section_key}" is now ${is_visible ? "visible" : "hidden"}.` }],
      structuredContent: { section: data[0] }
    };
  }
});

// src/lib/mcp/tools/list-listings.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var list_listings_default = defineTool5({
  name: "list_rental_listings",
  title: "List rental listings",
  description: "List the Malta rental properties currently published in the Guesty booking engine, with title, city and nightly price.",
  inputSchema: {
    limit: z4.number().int().optional().describe("How many listings to return (default 12, max 50)."),
    city: z4.string().trim().optional().describe("Optional city filter, e.g. 'Sliema'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ limit, city }) => {
    const take = Math.min(Math.max(limit ?? 12, 1), 50);
    const qs = new URLSearchParams({ action: "listings", limit: String(take) });
    if (city) qs.set("city", city);
    const key = publishableKey();
    const res = await fetch(`${guestyEndpoint()}?${qs.toString()}`, {
      headers: { apikey: key, Authorization: `Bearer ${key}`, Accept: "application/json" }
    });
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `Booking engine error ${res.status}` }],
        isError: true
      };
    }
    const data = await res.json();
    const results = data?.results ?? data?.data ?? [];
    const listings = results.slice(0, take).map((l) => ({
      id: l._id ?? l.id,
      title: l.title ?? l.nickname ?? "Untitled",
      city: l.address?.city ?? null,
      bedrooms: l.bedrooms ?? null,
      accommodates: l.accommodates ?? null,
      nightly_price: l.prices?.basePrice ?? null,
      currency: l.prices?.currency ?? null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(listings, null, 2) }],
      structuredContent: { listings, count: listings.length }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ceodzfohpstddpnqmoqu";
var mcp_default = defineMcp({
  name: "remix-of-remix-of-remix-of-remix-of-vincenti-brand-logo",
  title: "Remix of Remix of Remix of Remix of Vincenti Brand Logo",
  version: "0.1.0",
  instructions: "Tools for the Christiano Property Management site. Read and edit CMS sections and pages (JSON block content), toggle section visibility, and browse live Guesty rental listings. Section keys prefixed 'page:' hold full page block arrays.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_sections_default,
    get_section_default,
    update_section_default,
    toggle_section_default,
    list_listings_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
